from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[2]
ART=ROOT/"Result/artifacts/0_25_evidence_grade_readiness.json"
SUB=ROOT/"Result/artifacts"
NAMES={"source_and_panel":"0_25_uet_economics_verification.json","measurement_validity":"0_25_uet_measurement_validity_audit.json","causal_identification":"0_25_causal_identification_gate.json","global_replication":"0_25_global_replication_readiness.json","independent_replication":"0_25_independent_replication_gate.json","publication_review":"0_25_publication_hardening_gate.json","regional_robustness":"0_25_global_wdi_leave_one_region_out.json","imf_cpi_coverage":"0_25_global_imf_cpi_coverage.json","imf_wdi_normalization":"0_25_global_imf_wdi_normalization.json","funding_proxy_panel":"0_25_funding_source_proxy_panel.json","funding_flow_gate":"0_25_funding_source_flow_gate.json","fed_z1_source_probe":"0_25_fed_z1_source_probe.json","fed_z1_funding_mapping":"0_25_fed_z1_funding_mapping_probe.json","bls_io_source_gate":"0_25_bls_io_source_gate.json","fed_z1_funding_mix":"0_25_fed_z1_funding_mix_audit.json","payer_resource_join":"0_25_payer_resource_join_readiness.json","bea_1997_io_benchmark":"0_25_bea_1997_io_benchmark_audit.json","bls_industry_hours":"0_25_bls_industry_hours_source_package.json","usaspending_federal_award_ledger":"0_25_usaspending_federal_project_ledger.json","treasury_funding_source":"0_25_treasury_funding_source_audit.json","award_outlay_reconciliation":"0_25_federal_award_outlay_reconciliation.json","award_level_outlay":"0_25_usaspending_award_level_outlay_audit.json","award_funding_account":"0_25_usaspending_award_funding_account_audit.json","usgs_material_quantities":"0_25_usgs_material_quantity_audit.json","sec_public_firm_funding_proxy":"0_25_sec_public_firm_funding_proxy.json","sec_public_firm_funding_mix":"0_25_sec_public_firm_funding_mix_audit.json","project_payment_ledger":"0_25_project_payment_ledger_gate.json"}
def main():
 checks={}
 for k,n in NAMES.items():
  d=json.loads((SUB/n).read_text(encoding="utf-8"));checks[k]=d.get("status")
 critical=[k for k,v in checks.items() if v not in {"PASS","DIAGNOSTIC_COMPLETE"}]
 out={"schema_version":"1.0","topic":"0.25_Strategy_Power_Economics","status":"BLOCKED" if critical else "CANDIDATE","target":"Evidence Grade A","checks":checks,"controlling_blockers":critical,"promotion_rule":"All critical source, measurement, causal, global, independent-replication, and publication checks must be PASS; no WARN/BLOCKED critical gate may be averaged away.","claim_boundary":"Current evidence supports only source-locked descriptive diagnostics. This readiness artifact does not promote Claim Class C."};ART.write_text(json.dumps(out,indent=2)+'\n',encoding='utf-8');print('Evidence Grade readiness:',out['status'],critical)
if __name__=="__main__":main()
